### ISSUE TITLE
doesn't support long presses!

### ISSUE THREAD

**Issue by a-eid** [JonnyBurger/touchable-scale#1]
@JonnyBurger great work, 

one thing is that the lib doesn't appear to be supporting long presses.

**Comment by JonnyBurger** [comment]
Thanks for the report, that's true, I believe other events are not supported on Android.
I think there is nothing I can do to fix it because of this issue: https://github.com/software-mansion/react-native-gesture-handler/issues/920

I have documented this in the README now.
Maybe check out https://github.com/sa8ab/react-native-scale-button, an implementation using Reanimated 2 that uses LongPressGestureHandler

**Comment by a-eid** [comment]
@JonnyBurger this is still a bug in this package ( I would reopen ), you can opt out of using a `TapGestureHandler` and rather use a `TouchableX` which has an `onPress` as well as `onLongPress` by default.

however I wouldn't like to not think about your implementation and just use the lib,

thank you.

**Comment by JonnyBurger** [comment]
Do you have an example of how the component could support this cleanly?
Happy to reopen if you have an idea on how to solve it.

**Comment by a-eid** [comment]
sure, let me test a couple of ideas first, I'll submit a PR.

**Comment by JonnyBurger** [comment]
v0.7.0 now supports long presses! 🎉
